/**
 * KarimeKumagaiRevopsEn — EN-US Personal variant for Karime Kumagai.
 *
 * Generated by squad ghostwriter-linkedin-auto v1.6.0 (Cleidim, step-05d)
 * for run 2026-05-13-karime-kumagai-en-us. Single variant: en + personal
 * (Karime collaborator.language=['en-us'], rotation selected en-us).
 *
 * Speaker badge top-left mantido via BrandFrame (mode='personal' + speaker
 * info no spec.context). Logo Luby auto-suprimido em logo-mark e
 * closing-card via useCurrentAccountMode().
 */

import React from 'react';
import { VideoRenderer } from '../renderer/VideoRenderer';
import { karimeKumagaiRevopsEnSpec } from '../schema/examples/karime-kumagai-revops-en';
import type { CommonProps } from './types';

export const KarimeKumagaiRevopsEn: React.FC<CommonProps> = ({ lang, mode, speaker }) => {
  return (
    <VideoRenderer
      spec={karimeKumagaiRevopsEnSpec}
      overrides={{ lang, mode, speaker }}
    />
  );
};
