/**
 * RodrigoGardinSubstrateEn — EN-US Personal variant for Rodrigo Gardin.
 *
 * Generated by squad ghostwriter-linkedin-auto v1.6.0 (Cleidim, step-05d)
 * for run 2026-05-13-rodrigo-gardin-en-us. Single variant: en + personal.
 *
 * Rodrigo bilingual (collaborator.language=['en-us','pt-br']) but rotation
 * default = first element = en-us (no prior video history).
 */

import React from 'react';
import { VideoRenderer } from '../renderer/VideoRenderer';
import { rodrigoGardinSubstrateEnSpec } from '../schema/examples/rodrigo-gardin-substrate-en';
import type { CommonProps } from './types';

export const RodrigoGardinSubstrateEn: React.FC<CommonProps> = ({ lang, mode, speaker }) => {
  return (
    <VideoRenderer
      spec={rodrigoGardinSubstrateEnSpec}
      overrides={{ lang, mode, speaker }}
    />
  );
};
