/**
 * Audio asset manifest.
 *
 * The JSON file at public/audio/manifest.json is generated by the audio
 * pipeline (`npm run audio:generate` / `npm run audio:narrate`). This
 * module wraps it in a typed import so the rest of the app reads asset
 * metadata with autocomplete instead of stringly-typed file paths.
 *
 * If the manifest doesn't exist yet (first install, before generation),
 * we fall back to an empty manifest so the project still renders — the
 * video just won't have audio. That keeps `npm start` working immediately
 * after `git clone` without forcing every contributor to run the audio
 * pipeline first.
 */

import manifestJson from '../../public/audio/manifest.json';

export interface AudioAsset {
  id: string;
  /** Path relative to public/audio/, e.g. "bgm/corporate-tech-uplifting-1.mp3". */
  file: string;
  duration_s: number;
  prompt: string;
}

export interface NarrationClip {
  /** Path relative to public/audio/, e.g. "narration/pt/intro.mp3". */
  file: string;
  /** The text that was synthesized. Useful for accessibility tracks. */
  text: string;
}

/**
 * Narration is keyed by language ('pt' | 'en') then by scene key
 * ('intro' | 'hook' | 'bullets' | 'stat' | 'cta'). A scene without a
 * narration clip simply isn't present in the inner object.
 */
export type NarrationByLang = Record<string, Record<string, NarrationClip>>;

export interface AudioManifest {
  generatedAt: string;
  bgm: AudioAsset[];
  sfx: AudioAsset[];
  narration?: NarrationByLang;
}

export const manifest: AudioManifest = manifestJson as AudioManifest;

/**
 * Find an asset by id. Returns undefined if not found (e.g. the manifest
 * predates this id, or the asset was never generated). Callers should
 * handle undefined gracefully — typically by skipping the audio entirely.
 */
export const findBgm = (id: string): AudioAsset | undefined =>
  manifest.bgm.find((b) => b.id === id);

export const findSfx = (id: string): AudioAsset | undefined =>
  manifest.sfx.find((s) => s.id === id);

/**
 * Find a narration clip for a given language + scene key. Returns
 * undefined if narration hasn't been generated for this combination,
 * which the caller should treat as "skip narration here".
 */
export const findNarration = (
  lang: string,
  sceneKey: string,
): NarrationClip | undefined => {
  const perLang = manifest.narration?.[lang.toLowerCase()];
  return perLang?.[sceneKey];
};

/**
 * Default BGM track for a video. Picks the first available track from
 * the manifest. To rotate manually, pass a specific id to <VideoAudio>.
 */
export const defaultBgmId = (): string | null =>
  manifest.bgm[0]?.id ?? null;
